version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python ./script/manage.py runserver --settings=app.settings-test 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
        - db
