version: '3'

services:
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
    depends_on:
        - webserver
  webserver:
    env_file:
      - 'variables.env'
    build: ./webserver
    command: ./run_server ${DB_HOST}
    volumes:
      - ./webserver:/code
    ports:
      - "8000:8000"
