version: '3'

services:
  db:
    env_file:
      - 'variables.env'
    image: postgres
  web:
    env_file:
      - 'variables.env'
    build: ./script
    command: python manage.py runserver --settings=app.settings.test 0.0.0.0:8000
    volumes:
      - ./script:/code
    ports:
      - "8000:8000"
    depends_on:
        - db
