version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/SCRIPT
    steps:
      - checkout      
      - run: 
          name: Run Unit Tests
          command: python -m unittest
          
  deploy:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/SCRIPT
    steps:
      - run: |
          echo "Hello, I'm not deploying yet, but that's ok, I will soon..."

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
