# Generated by Django 2.2.4 on 2020-08-11 18:53

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import script.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingport',
            name='connector',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('CHAdeMO', 'CHAdeMO'), ('Combo', 'Combo'), ('J1772', 'J1772'), ('Unknown', 'Unknown')], default=script.models.enums.ChargingConnector('Unknown'), enum_class=script.models.enums.ChargingConnector, max_length=7),
        ),
        migrations.AlterField(
            model_name='loadforecastconfig',
            name='aggregation_level',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('state', 'state'), ('county', 'county'), ('zip', 'zip')], default=script.models.enums.AggregationLevel('county'), enum_class=script.models.enums.AggregationLevel, max_length=6),
        ),
        migrations.AlterField(
            model_name='loadprofileconfig',
            name='day_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('weekday', 'weekday'), ('weekend', 'weekend'), ('peak', 'peak')], default=script.models.enums.DayType('weekday'), enum_class=script.models.enums.DayType, max_length=7),
        ),
        migrations.AlterField(
            model_name='loadprofileconfig',
            name='poi',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('All', 'All'), ('Workplace', 'Workplace'), ('DC Fast Charger', 'DC Fast Charger'), ('Residential', 'Residential'), ('Public L2', 'Public L2'), ('Unknown', 'Unknown')], default=script.models.enums.POI('Unknown'), enum_class=script.models.enums.POI, max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ev_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('PLUGIN', 'PLUGIN'), ('HYBRID', 'HYBRID'), ('UNKNOWN', 'UNKNOWN')], default=script.models.enums.EVType('UNKNOWN'), enum_class=script.models.enums.EVType, max_length=7),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Nissan', 'Nissan'), ('Chevrolet', 'Chevrolet'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Honda', 'Honda'), ('Unknown', 'Unknown')], default=script.models.enums.VehicleMake('Unknown'), enum_class=script.models.enums.VehicleMake, max_length=9),
        ),
    ]
